# Generated by Django 4.0.1 on 2022-01-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=20)),
            ],
        ),
    ]
